---
apiVersion: apps/v1
kind: Deployment
metadata:
	name: comments-api
spec:
	replicas: 3
	strategy:
		type: RollingUpdate
		rollingUpdate:
			maxSurge: 1
			maxUnavailable: 0
	selector:
		matchLabels:
			name: comments-rest-api
	template:
		metadata:
			labels:
				name: comments-rest-api
		spec:
			containers:
			- name: application
				image: "shortdaddy0711/comments-rest-api:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080